CREATE DATABASE USERMANAGEMENT
USE USERMANAGEMENT
CREATE TABLE UserAccounts (
    UserId INT IDENTITY(1,1) PRIMARY KEY,
    FullName NVARCHAR(100) NOT NULL,
    EmailOrPhone NVARCHAR(100) NOT NULL,
    Username NVARCHAR(100) NOT NULL UNIQUE,
    Password NVARCHAR(100) NOT NULL
)