USE [master]
GO
/****** Object:  Database [USERMANAGEMENT]    Script Date: 10/2/2025 10:21:48 PM ******/
CREATE DATABASE [USERMANAGEMENT]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'USERMANAGEMENT', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\USERMANAGEMENT.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'USERMANAGEMENT_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\USERMANAGEMENT_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [USERMANAGEMENT] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [USERMANAGEMENT].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [USERMANAGEMENT] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [USERMANAGEMENT] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [USERMANAGEMENT] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [USERMANAGEMENT] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [USERMANAGEMENT] SET ARITHABORT OFF 
GO
ALTER DATABASE [USERMANAGEMENT] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [USERMANAGEMENT] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [USERMANAGEMENT] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [USERMANAGEMENT] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [USERMANAGEMENT] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [USERMANAGEMENT] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [USERMANAGEMENT] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [USERMANAGEMENT] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [USERMANAGEMENT] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [USERMANAGEMENT] SET  ENABLE_BROKER 
GO
ALTER DATABASE [USERMANAGEMENT] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [USERMANAGEMENT] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [USERMANAGEMENT] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [USERMANAGEMENT] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [USERMANAGEMENT] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [USERMANAGEMENT] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [USERMANAGEMENT] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [USERMANAGEMENT] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [USERMANAGEMENT] SET  MULTI_USER 
GO
ALTER DATABASE [USERMANAGEMENT] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [USERMANAGEMENT] SET DB_CHAINING OFF 
GO
ALTER DATABASE [USERMANAGEMENT] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [USERMANAGEMENT] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [USERMANAGEMENT] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [USERMANAGEMENT] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [USERMANAGEMENT] SET QUERY_STORE = ON
GO
ALTER DATABASE [USERMANAGEMENT] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [USERMANAGEMENT]
GO
/****** Object:  Table [dbo].[UserAccounts]    Script Date: 10/2/2025 10:21:48 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UserAccounts](
	[UserId] [int] IDENTITY(1,1) NOT NULL,
	[FullName] [nvarchar](100) NOT NULL,
	[EmailOrPhone] [nvarchar](100) NOT NULL,
	[Username] [nvarchar](100) NOT NULL,
	[Password] [nvarchar](100) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[UserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [UQ__UserAcco__536C85E4396C6AA2]    Script Date: 10/2/2025 10:21:49 PM ******/
ALTER TABLE [dbo].[UserAccounts] ADD UNIQUE NONCLUSTERED 
(
	[Username] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [USERMANAGEMENT] SET  READ_WRITE 
GO
